version: '3'
services:
  db:
    image: arm64v8/mariadb:latest 
    container_name: "mysql_test"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mysql_test_db
        MYSQL_USER: admin
        MYSQL_PASSWORD: secret
        TZ: 'Asia/Tokyo'
    ports:
        - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data_test:/var/lib/mysql
      - db_my.cnf_test:/etc/mysql/conf.d/my.cnf
      - db_sql_test:/docker-entrypoint-initdb.d

  php:
    build: ./docker/php
    container_name: "php-fpm"
    volumes:
      - ./src:/var/www

  nginx:
    image: arm64v8/nginx:latest
    container_name: "nginx_test"
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin_test"
    environment:
      - PMA_ARBITRARY=1 
      - PMA_HOST=db
      - PMA_USER=admin 
      - PMA_PASSWORD=secret
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

  node:
    image: arm64v8/node:latest
    container_name: "node14.18-alpine"
    tty: true
    volumes:
      - ./src:/var/www
    working_dir: /var/www

  mail:
    image: mailhog/mailhog:latest
    container_name: "mailhog"
    ports:
      - 8025:8025

volumes:
  db_data_test:
  db_my.cnf_test:
  db_sql_test: